###
POST http://localhost:3000/universities/register

###
GET http://localhost:3000/universities

###
GET http://localhost:3000/universities?country=Argentina

###
GET http://localhost:3000/universities?page=2

###
GET http://localhost:3000/universities?country=Argentina&page=2

###

GET http://localhost:3000/universities/6310105b17caba44eb0b5841

###

POST http://localhost:3000/universities
Content-Type: application/json

{
    "alpha_two_code": "BR",
    "web_pages": ["http://www.cambridge.com", "http://www.cambridgeBR.com", "http://www.cambridgeUS.com"],
    "name": "Universidade de Suzano",
    "country": "Brazil",
    "domains": ["www.Suzano.com", "www.Suzano.uni", "www.CambridgeUni.com"],
    "state_province": "SP"
}

###

PUT http://localhost:3000/universities/6310105b17caba44eb0b5841
Content-Type: application/json

{
    "web_pages": ["teste", "teste2", "teste3"],
    "name": "Universidade Teste Alterar2",
    "domains": ["www.Teste.com", "www.dokimí.com", "www.Prüfung.com"]
}

###
DELETE http://localhost:3000/universities/6310105b17caba44eb0b5841

###

DELETE http://localhost:3000/universitiesDeleteAll

###
